include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    require_trailing_commas: true

analyzer:
  errors:
    # avoid_types_as_parameter_names: ignore
    invalid_annotation_target: ignore
    # unused_element: ignore
    use_build_context_synchronously: ignore
  exclude: [lib/**.g.dart, lib/**.freezed.dart, android/]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
