name: digibuzz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  collection: ^1.18.0
  dio: ^5.7.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.20.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  marquee: ^2.3.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  video_player: ^2.9.2
  scrolling_text: ^0.0.4
  nepali_date_picker: ^6.0.1
  location: ^7.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
